name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  build_skim:
    needs: greeting
    runs-on: ubuntu-latest
    container: rootproject/root:${{ matrix.version }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      matrix:
        version: [6.22.06-conda]
        allow_failure: [false]
        include:
          - version: latest
            allow_failure: true
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: build
        run: |
          COMPILER=$(root-config --cxx)
          FLAGS=$(root-config --cflags --libs)
          $COMPILER -g -o3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS
      - uses: actions/upload-artifact@v2
        with:
          name: skim${{ matrix.version }}
          path: skim
          
  skim:
    needs: build_skim
    runs-on: ubuntu-latest
    container: rootproject/root:6.22.06-conda
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - uses: action/download-artifact@v2
        with:
          name: skim${{ matrix.version }}
      - name: skim
        run: |
          chmod +x ./skim
          ./skim
